### ISSUE TITLE
Proton makes almost-empty prefixes

### ISSUE THREAD

**Issue by CartoonFan** [Frogging-Family/wine-tkg-git#374]
Hey there, @Tk-Glitch! I'm back with another fun Proton bug. Basically, after applying the fix in #370, Proton started creating more or less empty prefixes:

```console
$ ls -lv /home/jeremiah/.local/share/Steam/steamapps/compatdata/743890
total 0
drwxr-xr-x 3 jeremiah jeremiah 0 May 16 12:10 pfx
-rwxr-xr-x 1 jeremiah jeremiah 0 May 16 12:10 pfx.lock
```

```console
$ ls -lv /home/jeremiah/.local/share/Steam/steamapps/compatdata/743890/pfx
total 0
drwxr-xr-x 2 jeremiah jeremiah 0 May 16 12:10 drive_c
```

```console
$ ls -lv /home/jeremiah/.local/share/Steam/steamapps/compatdata/743890/pfx/drive_c 
total 0
```

And here's the relevant console output:

```console
Launching appid 743890
Loaded Config for Local Selection Path for App ID 743890, Controller 0: /home/jeremiah/.local/share/Steam//controller_base/templates/controller_xbox360_gamepad_joystick.vdf
Failed to open digital audio driver Couldn't open OAL device.
GameAction [AppID 743890, ActionID 2] : LaunchApp changed task to BPMHybridOverlay10ftShutdown with ""
Loaded Config for Local Selection Path for App ID 743890, Controller 0: /home/jeremiah/.local/share/Steam//controller_base/templates/controller_xbox360_gamepad_joystick.vdf
GameAction [AppID 743890, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
src/clientdll/installscript_posix.cpp (357) : Assertion Failed: strCommonRedistForeignInstallPath != ""
Slow image load - /home/jeremiah/.local/share/Steam/tenfoot/resource/images/library/play_action_modal_mask.png (dimensions 1920x1080, took 22 msec)
Proton: Upgrading prefix from None to 6.8-5 (/home/jeremiah/.local/share/Steam/steamapps/compatdata/743890/)
Traceback (most recent call last):
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 1223, in <module>
    g_session.init_session()
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 983, in init_session
    g_compatdata.setup_prefix()
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 433, in setup_prefix
    os.symlink("../drive_c", self.prefix_dir + "/dosdevices/c:")
FileNotFoundError: [Errno 2] No such file or directory: '../drive_c' -> '/home/jeremiah/.local/share/Steam/steamapps/compatdata/743890/pfx//dosdevices/c:'
Proton: Upgrading prefix from None to 6.8-5 (/home/jeremiah/.local/share/Steam/steamapps/compatdata/743890/)
Traceback (most recent call last):
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 1223, in <module>
    g_session.init_session()
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 983, in init_session
    g_compatdata.setup_prefix()
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 433, in setup_prefix
    os.symlink("../drive_c", self.prefix_dir + "/dosdevices/c:")
FileNotFoundError: [Errno 2] No such file or directory: '../drive_c' -> '/home/jeremiah/.local/share/Steam/steamapps/compatdata/743890/pfx//dosdevices/c:'
src/clientdll/installscript_posix.cpp (419) : Assertion Failed: Standalone evaluator returned error code for app 743890
src/clientdll/installscript_posix.cpp (419) : Assertion Failed: Standalone evaluator returned error code for app 743890
GameAction [AppID 743890, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 743890, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 743890, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 743890, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 743890, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 743890 "", ProcID 2077648, IP 0.0.0.0:0
ERROR: ld.so: object '/home/jeremiah/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jeremiah/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/jeremiah/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Proton: Upgrading prefix from None to 6.8-5 (/home/jeremiah/.local/share/Steam/steamapps/compatdata/743890/)
Traceback (most recent call last):
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 1223, in <module>
    g_session.init_session()
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 983, in init_session
    g_compatdata.setup_prefix()
  File "/usr/share/steam/compatibilitytools.d/proton_tkg_makepkg/proton", line 433, in setup_prefix
    os.symlink("../drive_c", self.prefix_dir + "/dosdevices/c:")
FileNotFoundError: [Errno 2] No such file or directory: '../drive_c' -> '/home/jeremiah/.local/share/Steam/steamapps/compatdata/743890/pfx//dosdevices/c:'
Starting app 743890
Loaded Config for Local Selection Path for App ID 743890, Controller 0: /home/jeremiah/.local/share/Steam//controller_base/templates/controller_xbox360_gamepad_joystick.vdf
>>> Adding process 2077648 for game ID 743890
GameAction [AppID 743890, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
>>> Adding process 2077649 for game ID 743890
GameAction [AppID 743890, ActionID 2] : LaunchApp changed task to Completed with ""
Game removed: AppID 743890 "", ProcID 2077648 
Uploaded AppInterfaceStats to Steam
Exiting app 743890
No cached sticky mapping in ActivateActionSet.No cached sticky mapping in ActivateActionSet.OnFocusWindowChanged to window type: k_nGameIDControllerConfigs_Desktop, AppID 413080
Loaded Config for Local Selection Path for App ID 413080, Controller 0: /home/jeremiah/.local/share/Steam/steamapps/workshop/content/241100/922638163/818937737353552570_legacy.bin
Slow image load - https://steamstore-a.akamaihd.net/fulldetailsheader/743890/header_t_0.jpg (dimensions 1280x720, took 51 msec)
```

An interesting workaround is that, if I try to run a game and run protontricks afterwards, protontricks fills out the prefix, and Steam can play the game just fine, so it seems that Proton can't make prefixes itself for some reason. I'm using commit 43e8006e6f0f544ac1b5912c661bb0661a7716d2. Thanks as always and sorry for the long post.

**Comment by Tk-Glitch** [comment]
This is still a makepkg build I suppose?

**Comment by CartoonFan** [comment]
That's correct!

**Comment by CartoonFan** [comment]
So, I just tested the latest commit, and it seems like it works. I'm kind of wondering what happened to the makepkg builds, though. I've been using them for a while with no issues, so this seems somewhat unexpected.

Also, on a related note, is the proton-tkg script the preferred way to build now?

**Comment by Tk-Glitch** [comment]
> So, I just tested the latest commit, and it seems like it works.

I'm glad! Feel free to close the issue :)

> I've been using them for a while with no issues, so this seems somewhat unexpected.

There has been quite a few changes on both upstream wine and proton regarding paths and prefix handling, and with makepkg builds limitations needing workarounds every time I'm not that surprised.

> Also, on a related note, is the proton-tkg script the preferred way to build now?

The PKGBUILD calls the script and adds hacks into the mix to make it work. Using the script directly has always been the preferred and recommended way, but due to popular demand, the pkgbuild way was added. I'm not personally using it (and won't), but I can see how some people could find it convenient as a pacman package.

**Comment by CartoonFan** [comment]
All right, good to know. Like you mentioned, I was using the makepkg build out of convenience, as I would otherwise have to select the newly built TkG build from Steam every time, but I can definitely give the script another try. Thanks for commenting and going out of your way to fix my issue as well 😀.

Closing #374!

**Comment by Tk-Glitch** [comment]
> as I would otherwise have to select the newly built TkG build from Steam every time

The uninstaller tool in the proton-tkg script (running automatically after compilation by default, but it can be triggered manually with `./proton-tkg.sh clean`) can handle upgrades fine. Uninstall your current build with it and it'll be replaced by the newer one.

**Comment by CartoonFan** [comment]
That's really good to know! I'll have to try that next time.
