### ISSUE TITLE
crash after applying wine-tkg-staging.patch

### ISSUE THREAD

**Issue by daci12345** [Frogging-Family/wine-tkg-git#786]
```
 -> Applying wine-tkg-staging.patch
 -> Removed BIG_UGLY_FROGMINER - Ribbit
```
crash log from prepare.log:

```
wine-tkg-staging.patch -- ( Please don't report bugs about this wine build on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead. )
patching file dlls/ntdll/loader.c
Hunk #1 succeeded at 4325 with fuzz 2 (offset 842 lines).

Running make_vulkan
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1425, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dlls/winevulkan/make_vulkan", line 3967, in <module>
    main()
  File "dlls/winevulkan/make_vulkan", line 3934, in main
    download_vk_xml(vk_xml)
  File "dlls/winevulkan/make_vulkan", line 3913, in download_vk_xml
    urllib.request.urlretrieve(url, filename)
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>
```

**Comment by Tk-Glitch** [comment]
The error happens while running `make_vulkan` (which is a script wine ships, not us). Your OS seems to have a SSL certificate issue. You can try to run `pip install --upgrade certifi` I guess. Sadly it's not something we can fix on our end.

**Comment by daci12345** [comment]
Thank you, it fixed it.

**Comment by Tk-Glitch** [comment]
Great!
