### ISSUE TITLE
electron games will fail to launch when using 5-17-staging

### ISSUE THREAD

**Issue by silverhikari** [Frogging-Family/wine-tkg-git#840]
when launching windows electron games with wine-5-17-staging the program fails with the following error log(this was made with a fresh wineprefix)

```
008c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
008c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
008c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
008c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
012c:fixme:powrprof:PowerRegisterSuspendResumeNotification (0x00000002,000000000011FCF0,000000000011FCE8) stub!
012c:fixme:heap:RtlSetHeapInformation handle 0000000000000000, info_class 1, info 0000000000000000, size 0 stub!
012c:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 000000000011F2E0, 0000000000000000 000000000011F2DC
012c:fixme:nls:get_dummy_preferred_ui_language (0x38 000000000011F2E0 0000000000000000 000000000011F2DC) returning a dummy value (current locale)
012c:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 000000000011F2E0, 000000000210E850 000000000011F2DC
012c:fixme:nls:get_dummy_preferred_ui_language (0x38 000000000011F2E0 000000000210E850 000000000011F2DC) returning a dummy value (current locale)
013c:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 00000000036FFE10
012c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
fs.js:115
    throw err;
    ^

Error: EINVAL: invalid argument, lstat 'Z:\'
    at realpathSync (fs.js:1393:5)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:318:24)
    at toRealPath (internal/modules/cjs/loader.js:205:13)
    at Function.Module._findPath (internal/modules/cjs/loader.js:271:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:25)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:759:3)
012c:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000011EC10
```
this problem does not happen when using wine 5-17 and lower

**Comment by Tk-Glitch** [comment]
Are we talking about Wine 7.15 here?
5.17 is two years old at this point and nobody will fix an issue affecting that specific version. If the issue happens on 7.15 staging though, that's worth bisecting.

**Comment by silverhikari** [comment]
yep, i mixed up the numbers sorry!

**Comment by silverhikari** [comment]
> Are we talking about Wine 7.15 here? 5.17 is two years old at this point and nobody will fix an issue affecting that specific version. If the issue happens on 7.15 staging though, that's worth bisecting.

i mixed up the numbers what i had mean't was 7.15

**Comment by Tk-Glitch** [comment]
That's one interesting error log. Bisecting is needed.

**Comment by silverhikari** [comment]
just checked and this is still a issue on wine-tkg-staging 7.19 though the error log seems to be less now. it seems the main issue is this part:
```
01d0:fixme:ver:GetPackageFamilyName (FFFFFFFFFFFFFFFF 000000000011F21C 000000000011F220): stub
fs.js:115
    throw err;
    ^

Error: EINVAL: invalid argument, lstat 'Z:\'
    at realpathSync (fs.js:1393:5)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:318:24)
    at toRealPath (internal/modules/cjs/loader.js:205:13)
    at Function.Module._findPath (internal/modules/cjs/loader.js:271:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:25)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:759:3)
01d0:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000011EC10
```

**Comment by silverhikari** [comment]
i have found the patchsets that seem to be causing this error as disabling them allows the game to fully load. the two patchsets are "eventfd_synchronization" and "ntdll-Junction_Points"

**Comment by Tk-Glitch** [comment]
It's unlikely to be `eventfd_synchronization` but it soft depends on `ntdll-Junction_Points`, which is the likely culprit. I guess we could make a custom patch to break that soft dependency again (we used to have that in place before due to `ntdll-Junction_Points` breaking stuff already, but the specific breakage was fixed).
Thanks for finding out.
