### ISSUE TITLE
Games Failing nvapi64.dll not found

### ISSUE THREAD

**Issue by shaumux** [Frogging-Family/wine-tkg-git#922]
With a new build games have started failing with an error saying nvapi64.dll not found even though I use an AMD gpu 
The error is this 
```
/bin/sh\0-c\0gamemoderun WINEDEBUG=warn+all PROTON_LOG=1 MANGOHUD=1 MANGOHUD_CONFIG=fps,gamepad_battery,gamemode,ram,vram,vulkan_driver,wine PROTON_DXVK_ASYNC=1 /home/shaumux/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1151640 -- /home/shaumux/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/shaumux/.local/share/Steam/compatibilitytools.d/proton_tkg_7.22.r7.gf912827a'/proton waitforexitandrun  '/media/Games/Linux/SteamLibrary/steamapps/common/Horizon Zero Dawn/HorizonZeroDawn.exe'\0
Game process added : AppID 1151640 "gamemoderun WINEDEBUG=warn+all PROTON_LOG=1 MANGOHUD=1 MANGOHUD_CONFIG=fps,gamepad_battery,gamemode,ram,vram,vulkan_driver,wine PROTON_DXVK_ASYNC=1 /home/shaumux/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1151640 -- /home/shaumux/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/shaumux/.local/share/Steam/compatibilitytools.d/proton_tkg_7.22.r7.gf912827a'/proton waitforexitandrun  '/media/Games/Linux/SteamLibrary/steamapps/common/Horizon Zero Dawn/HorizonZeroDawn.exe'", ProcID 14518, IP 0.0.0.0:0
chdir /media/Games/Linux/SteamLibrary/steamapps/common/Horizon Zero Dawn
ERROR: ld.so: object '/home/shaumux/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/shaumux/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/shaumux/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/shaumux/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
gamemodeauto: 
ERROR: ld.so: object '/home/shaumux/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/shaumux/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
gamemodeauto: 
ERROR: ld.so: object '/home/shaumux/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
gamemodeauto: 
ERROR: ld.so: object '/home/shaumux/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
gamemodeauto: 
GameAction [AppID 1151640, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 1151640, ActionID 1] : LaunchApp changed task to Completed with ""
Traceback (most recent call last):
  File "/home/shaumux/.local/share/Steam/compatibilitytools.d/proton_tkg_7.22.r7.gf912827a/proton", line 1908, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/shaumux/.local/share/Steam/compatibilitytools.d/proton_tkg_7.22.r7.gf912827a/proton", line 1633, in init_session
    g_compatdata.setup_prefix()
  File "/home/shaumux/.local/share/Steam/compatibilitytools.d/proton_tkg_7.22.r7.gf912827a/proton", line 1097, in setup_prefix
    try_copy(g_proton.lib64_dir + "wine/nvapi/nvapi64.dll", "drive_c/windows/system32",
  File "/home/shaumux/.local/share/Steam/compatibilitytools.d/proton_tkg_7.22.r7.gf912827a/proton", line 163, in try_copy
    copyfile(src, dst)
  File "/home/shaumux/.local/share/Steam/compatibilitytools.d/proton_tkg_7.22.r7.gf912827a/proton", line 225, in copyfile_reflink
    with open(srcname, 'rb', buffering=0) as src:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shaumux/.local/share/Steam/compatibilitytools.d/proton_tkg_7.22.r7.gf912827a/files/lib64/wine/nvapi/nvapi64.dll'
Game process removed: AppID 1151640 "gamemoderun WINEDEBUG=warn+all PROTON_LOG=1 MANGOHUD=1 MANGOHUD_CONFIG=fps,gamepad_battery,gamemode,ram,vram,vulkan_driver,wine PROTON_DXVK_ASYNC=1 /home/shaumux/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1151640 -- /home/shaumux/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/shaumux/.local/share/Steam/compatibilitytools.d/proton_tkg_7.22.r7.gf912827a'/proton waitforexitandrun  '/media/Games/Linux/SteamLibrary/steamapps/common/Horizon Zero Dawn/HorizonZeroDawn.exe'", ProcID 14518 
ThreadGetProcessExitCode: no such process 14524
Uploaded AppInterfaceStats to Steam

```
The config I used 
[proton-tkg.cfg.log](https://github.com/Frogging-Family/wine-tkg-git/files/10200329/proton-tkg.cfg.log)
[proton-tkg.log](https://github.com/Frogging-Family/wine-tkg-git/files/10200331/proton-tkg.log)

**Comment by Tk-Glitch** [comment]
Your GPU doesn't matter as Proton will try to copy/enable the nvapi dlls for a selection of games independently. Is the behavior the same with `PROTON_ENABLE_NVAPI=0` set?
