### ISSUE TITLE
build error of wine-tkg staging 32bit side of build

### ISSUE THREAD

**Issue by rchris494** [Frogging-Family/wine-tkg-git#998]
it builds the 64 bit version just fine but when goes to build the 32bit version i get the following error

Removing texlive-pictures (2021.20220204-1) ...
Removing ubuntu-advantage-desktop-daemon (1.10~22.04.1) ...
Removing ubuntu-drivers-common (1:0.9.6.1) ...
Removing ubuntu-session (42.0-1ubuntu2) ...
Removing valgrind (1:3.18.1-1ubuntu2) ...
Removing ubuntu-advantage-tools (27.14.4~22.04) ...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python3/dist-packages/uaclient/apt.py", line 14, in <module>
    import apt  # type: ignore
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
dpkg: error processing package ubuntu-advantage-tools (--remove):
 installed ubuntu-advantage-tools package pre-removal script subprocess returned error exit status 1
dpkg: too many errors, stopping
Errors were encountered while processing:
 ubuntu-advantage-tools
Processing was halted because there were too many errors.
E: Sub-process /usr/bin/dpkg returned an error code (1)
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done

any suggestions?

**Comment by rchris494** [comment]
i guess the auto builds also fail at the same spot.

(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 289202 files and directories currently installed.)
Removing python3-apport (2.20.11-0ubuntu82.4) ...
Removing update-notifier-common (3.192.54.6) ...
Removing update-manager-core (1:22.04.10) ...
dpkg: warning: while removing update-manager-core, directory '/var/lib/update-manager' not empty so not removed
Removing ubuntu-advantage-tools (27.14.4~22.04) ...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python3/dist-packages/uaclient/apt.py", line 14, in <module>
    import apt  # type: ignore
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
dpkg: error processing package ubuntu-advantage-tools (--remove):
 installed ubuntu-advantage-tools package pre-removal script subprocess returned error exit status 1
dpkg: too many errors, stopping
Errors were encountered while processing:
 ubuntu-advantage-tools
Processing was halted because there were too many errors.
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done
yes: standard output: Broken pipe
Error: Process completed with exit code 100.

**Comment by d4nkf0x** [comment]
same problem have you tried editing this line '_nomakepkg_midbuild_prompt="false"' set it to "true"? what is the results?

**Comment by rchris494** [comment]
problem still remains the same changing that setting

Removing python3-tk:amd64 (3.10.6-1~22.04) ...
Removing python3-unicodedata2 (14.0.0+ds-8) ...
Removing texlive-formats-extra (2021.20220204-1) ...
Removing texlive-xetex (2021.20220204-1) ...
Removing texlive-latex-extra (2021.20220204-1) ...
Removing texlive-pictures (2021.20220204-1) ...
Removing ubuntu-advantage-desktop-daemon (1.10~22.04.1) ...
Removing ubuntu-drivers-common (1:0.9.6.1) ...
Removing ubuntu-session (42.0-1ubuntu2) ...
Removing valgrind (1:3.18.1-1ubuntu2) ...
Removing ubuntu-advantage-tools (27.14.4~22.04) ...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/lib/python3/dist-packages/uaclient/apt.py", line 14, in <module>
    import apt  # type: ignore
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
dpkg: error processing package ubuntu-advantage-tools (--remove):
 installed ubuntu-advantage-tools package pre-removal script subprocess returned error exit status 1
dpkg: too many errors, stopping
Errors were encountered while processing:
 ubuntu-advantage-tools
Processing was halted because there were too many errors.
E: Sub-process /usr/bin/dpkg returned an error code (1)
 -> Removed BIG_UGLY_FROGMINER - Ribbit
 -> Removed Proton-tkg token - Valve Ribbit
 -> exit cleanup done

**Comment by Tk-Glitch** [comment]
That `ubuntu-advantage-tools` package is not part of our dependency list, and it looks like the called python script is either frogged or requires yet another BS dependency coming out of nowhere.

**Comment by rchris494** [comment]
looks like Ubuntu 22.04.2 LTS is frogged..

**Comment by rchris494** [comment]
appears that ubuntu 22.04.2 iso seems to be good for building once again. i did not have any problems using that iso vs ubuntu 22.04.1 iso

**Comment by rchris494** [comment]
so i was able to play around with this some more the fix i found is run the following after installing ubuntu 22.04.02

apt purge ubuntu-advantage-tools -y && apt autoremove -y && apt update && apt full-upgrade -y && apt upgrade -y && apt dist-upgrade -y && apt autoremove -y && systemctl reboot

then you can go though the normal process for running a compile. i ran twice default-tkg without any errors. make sure to set debuntu as the OS in the .cfg
